FROM python:3.9
WORKDIR /app
COPY python/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY python/ .
COPY streaming.proto .
RUN python -m grpc_tools.protoc -I. --python_out=. --grpc_python_out=. streaming.proto