FROM python:3.9
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
# Compila os arquivos gRPC
RUN python -m grpc_tools.protoc -I. --python_out=. --grpc_python_out=. streaming.proto
CMD ["uvicorn", "rest_app:app", "--host", "0.0.0.0", "--port", "8000"]